In [1]:
import numpy as np
import scipy as sc
import random
#Definisikan array 11 x 11

#default array
A = [[random.randint(1,9) for i in range(11)] for j in range(11)]
print(A)
print("Tipe:", type(A))

#numpy
B = np.random.randint(1, 9, (11,11))
print(B)
print("Tipe:", type(B))

#scipy array
C = sc.array([[random.randint(1,9) for i in range(11)] for j in range(11)])
print(C)
print("Tipe:", type(C))

[[6, 2, 9, 4, 3, 2, 6, 1, 8, 4, 1], [7, 7, 2, 1, 6, 6, 4, 3, 2, 2, 4], [2, 6, 9, 7, 7, 5, 7, 4, 8, 8, 4], [5, 5, 4, 9, 1, 6, 4, 9, 7, 7, 1], [7, 5, 9, 5, 7, 3, 7, 8, 9, 9, 7], [8, 3, 3, 9, 2, 9, 8, 8, 9, 8, 6], [3, 2, 2, 9, 2, 5, 9, 7, 8, 8, 3], [5, 7, 8, 7, 6, 7, 2, 9, 9, 3, 3], [9, 1, 1, 8, 6, 4, 9, 4, 7, 1, 5], [6, 5, 6, 9, 4, 4, 6, 5, 3, 9, 9], [4, 5, 8, 2, 6, 4, 1, 2, 9, 7, 1]]
Tipe: <class 'list'>
[[7 3 7 1 8 2 8 1 3 5 1]
 [7 2 5 3 1 2 2 3 4 1 7]
 [2 6 1 7 1 6 3 2 7 2 2]
 [1 2 1 1 4 7 5 7 5 7 4]
 [8 8 8 3 5 4 3 7 6 4 2]
 [6 4 3 2 7 5 6 8 2 7 2]
 [6 7 4 3 7 8 2 5 6 8 4]
 [7 8 4 5 3 1 6 7 4 6 2]
 [6 4 4 1 6 2 3 3 6 1 1]
 [4 2 2 1 1 5 2 5 2 3 2]
 [4 7 4 8 3 1 6 8 7 5 8]]
Tipe: <class 'numpy.ndarray'>
[[6 5 9 8 5 6 2 3 3 2 5]
 [3 8 2 1 9 6 3 5 3 6 1]
 [4 7 5 1 1 4 3 1 7 9 1]
 [2 7 8 9 5 8 7 4 9 9 6]
 [8 2 2 8 8 8 5 2 2 5 6]
 [1 1 5 3 5 6 8 2 5 6 5]
 [3 5 7 9 8 1 8 5 1 5 5]
 [2 6 5 2 4 5 6 8 7 8 7]
 [3 4 1 9 1 7 1 8 2 2 2]
 [3 7 1 9 2 4 8 4 2 3 4]
 [2 7 7 9 1 5 1 4 3 8 8]]
Tipe: <clas

C:\Users\Dell\AppData\Local\Temp\ipykernel_3620\2082179155.py:17: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  C = sc.array([[random.randint(1,9) for i in range(11)] for j in range(11)])
